### ISSUE TITLE
adding medium sized thumbnails 

### ISSUE THREAD

**Issue by propertunist** [iionly/Elgg_1.8_tidypics#3]
after further exploring the issue i raised here: https://github.com/iionly/Elgg_1.8_tidypics/issues/2

i realise that the medium sized icons are needed for the plugin i am coding because the small size is generally needed to be quite small and the large size is pretty much full size which is too big to be truly used as an icon.

the blog_tools and videolist plugins both create medium sized icons and so it would be nice if tidypics did the same.

**Comment by iionly** [comment]
There is already kind of a "medium" sized thumbnail available. Though the size names are not exactly corresponding to the default Elgg image sizes. The corresponding size within Tidypics would be "small" which is by default a square size of 153px which is slightly larger than Elgg default size "medium" of 100px but surely much smaller than the Tidypics size "large" of 600px.

Summary of default sizes in Tidypics:
- "tiny" = 60px \* 60px,
- "small" = 153px \* 153px,
- "large" = 600px \* 600px,
- original size.

If you require any additional sizes, I'm afraid you'll have to modify Tidypics on your own. Right now I don't see a general necessity for additional thumbnail versions and I would like to avoid adding any because this would result first of all in additional disc space requirements.

**Comment by propertunist** [comment]
the intention is to ensure that tidypics is equal to the other elgg plugins so that the use of the various sizes of images that are available to other plugins are also available in tidypics.
